### ISSUE TITLE
Include modules from l10n_ar localizacion from Adhoc and Moldeo both working in 8.0

### ISSUE THREAD

**Issue by csrocha** [OCA/l10n-argentina#1]
Hello,

I request append the following modules to the OCA proyect in l10n-argentina.

https://github.com/odoo-l10n-ar 

https://github.com/ingadhoc/odoo-addons

One is organizated by @jjscarafia and me, @csrocha

Thanks,
Cristian.

**Comment by jjscarafia** [comment]
+ 1, this modules are also widely used by Argentina community. Any suggestiions on how to proceed?
Thanks,
Juan

**Comment by ivantodorovich** [comment]
@csrocha @jjscarafia @sebastiken No conviene unir fuerzas en una sola localización? 
La de ingadhoc esta bastante completa
