### ISSUE TITLE
Delete master branch

### ISSUE THREAD

**Issue by dreispt** [OCA/l10n-argentina#20]
OCA repos should not have a master branch, only released Odoo series branches.
Work for 8.0 should be in the 8.0 branch and master should be removed.

**Comment by dreispt** [comment]
cc @pedrobaeza

**Comment by pedrobaeza** [comment]
Done (you know who cc, because I'm going to be quick, hehe).

**Comment by dreispt** [comment]
@pedrobaeza :smile_cat:

**Comment by sebastiken** [comment]
:+1:
