### ISSUE TITLE
Error when trying to reject a check

### ISSUE THREAD

**Issue by gabrielo77** [OCA/l10n-argentina#31]
When I try to reject a check I get this error:

File "/home/gabriel/l10n-argentina/l10n_ar_account_check/wizard/check_reject.py", line 149, in action_reject
    invoice_vals['pos_ar_id'] = invoice_vals['pos_ar_id'] and invoice_vals['pos_ar_id'].id
AttributeError: 'int' object has no attribute 'id'

I also found an error on the translation message when a non-deposited check is being rejected.

**Comment by sebastiken** [comment]
This is closed and commit above.
