### ISSUE TITLE
License name 'GPL-3 or any later version' not supported

### ISSUE THREAD

**Issue by corsojulian7** [OCA/l10n-argentina#55]
License name 'GPL-3 or any later version' not supported in odoo 8.0, and not working

**Comment by pedrobaeza** [comment]
¿Qué módulo?

**Comment by corsojulian7** [comment]
En todos los módulos con string 'GPL-3 or any later version' en licencia
del __openerp__.py
Fue agregado en los últimos commits, y odoo lanza un traceback al querer
actualizar la lista de módulos en version 8.0

**Comment by pedrobaeza** [comment]
El fallo no es ése exactamente, si no otra licencia puesta con la palabra `other`. Resuelto en:

60a59bdc6cd53548f1428a5577d68f09aa9b1ba3

P.D: Esto proviene del requisito de especificar una licencia en el manifiesto para las Odoo Apps.
