### ISSUE TITLE
Al añadir cheques falta hacer obligatorios los campos fecha de emision y fecha de vencimiento

### ISSUE THREAD

**Issue by ckasimis** [OCA/l10n-argentina#7]
![crear cheque](https://cloud.githubusercontent.com/assets/12068859/8876060/a9bb50b6-31f3-11e5-838e-79e8b470e048.jpg)

Son datos obligatorios para un cheque por lo cual hay que hacerlos required=true

**Comment by ivantodorovich** [comment]
La fecha de pago no es obligatoria. Existen cheques no diferidos, donde la fecha de pago es -implícitamente- igual a la de emisión

**Comment by sebastiken** [comment]
@ckasimis buenas, se dejó sin el required porque comúnmente los _cheques_ se emiten con la misma fecha del _pago_. Por lo tanto, al usuario le es más rápida la carga _(algo muy importante para el usuario final)_. Como bien dice @ivantodorovich los _cheques no diferidos_ o _al día_, no requieren la carga de la _Fecha de Pago_. Para el caso de _cheques diferidos_, no estaría mal hacerlo _required_ en la vista, teniendo en cuenta el valor del campo _Tipo de Cheque_.
Si querés, @ckasimis podés abrir un _PR_ para esto, sino avisanos y si otros están de acuerdo con esta definición, lo hacemos.

cc @ssaid @kloss17 @gabrielo77 

Gracias por el aporte.

**Comment by gabrielo77** [comment]
@sebastiken vos decís hacer siempre requerida la _Fecha de Emisión_ y cuando es un _cheque diferido_ hacer la _Fecha de Pago_ también? O sólo para la _Fecha de Pago_ para el _cheque diferido_?

**Comment by ivantodorovich** [comment]
Yo trataría de simplificar el trabajo del usuario lo más posible. 
Ya que, en definitiva, esa es la finalidad de un sistema de gestión.

Con esa idea en mente, me haría algunas preguntas, y propondría otras mejoras:

Antes, una aclaración: no soy un usuario frecuente de este módulo, ya que nuestra empresa trabaja con la localización de ingadhoc, así que disculpen si en algunas cosas _"meo fuera del tarro"_, o que tampoco haga una PR. Sin embargo, con el espíritu de perfeccionar el sistema propongo poner en discusión esto.. y de más está decir que me gustaría ver algún día a todos los programadores argentinos combinando fuerzas en una única localización.

## 

#### Campo Tipo de Cheque

¿Cuál es el sentido de registrar si un cheque es diferido o no?
Sería más fácil para el usuario no tener que preocuparse por este campo. 

Si no es indispensable, dejaría el campo, pero cambiaría su valor por defecto para que sea _cheques diferidos_ (ya que es el más utilizado, casi en la mayoría de los casos)
Esto permitiría a un usuario avanzado _ocultar_ el campo en la vista, para las empresas a los que no les interesa registrar esto, y prefieren aliviar el trabajo de sus empleados.

## 

#### Campo Fecha de Pago

**Usabilidad:** Utilizaría la siguiente lógica (en las vistas):
- _Requerido_ y _Visible_ si el tipo de cheque es _diferido_, (valor por defecto)
- _No requerido_ y _Oculto_ si el tipo de cheque es _al día_.

**Comportamiento Interno:** Haría que el módulo se encargue _siempre_ de completar este campo, sin importar si el cheque es diferido o al día, usando la siguiente lógica:
- _Si el valor del campo no está presente, completarlo discretamente con el mismo valor que Fecha de Emisión_.

Esto permitiría simplificar código como este:

``` py
if check.type in 'common':
                aux_payment_date = check.issue_date
            elif check.payment_date:
                aux_payment_date = check.payment_date
            else:
                aux_payment_date = check.deposit_date
```

Ya que cualquier módulo dependiente, o reportes del usuario, podrían confiar siempre en `check.payment_date`. El código anterior se simplificaría a algo así:

``` py
aux_payment_date = check.payment_date or check.deposit_date
```

## 

#### Código de Bancos, Sucursal y Código Postal

La forma más rapida de ingresar un cheque en un sistema de gestión es leyendo el recuadro que se encuentra en la parte superior derecha del cheque:
![img_20160830_135447](https://cloud.githubusercontent.com/assets/1914185/18098771/f576a7ae-6eb9-11e6-9720-6f259f1fa374.jpg)

Donde se puede leer lo siguiente:

```
CodBanco (3 dígitos) - CodSucursal (3 dígitos) - CodPostal (4 dígitos)
Número de Cheque
Y otro número que desconozco
```

En la imágen que subí:

```
285 es el Código del Banco Macro
745 es el Código de la Sucursal del Banco que emitió la chequera
2156 es el Código Postal
58727807 es el Número de Cheque
```

**Un dato interesante:** La combinación de _CodBanco_, _CodSucursal_ + _Número de Cheque_ garantiza que no existan cheques duplicados. 

Es decir, en la práctica, pueden existir 2 cheques con el mismo número (_lo cual es raro, pero nos ha pasado_). Incluso pueden existir 2 cheques con el mismo número y código de banco (_lo cual es **muy** raro_), pero _nunca_(*) 2 cheques con el mismo número, código de banco y código de sucursal.

_(*) La verdad, no se si es una restricción real, o simplemente estadística. De todas formas, en mi experiencia, es fiable._

Con eso en mente:
- El campo _Banco_ debería solicitarse antes que el número de cheque, y debería poder ser buscado por su "_Código de Banco_", no sólo por su nombre.
- El campo _Sucursal_ debería solicitarse y ser requerido. Debería estar ubicado inmediatamente después que el campo banco, antes del número de cheque. Otro dato curioso: La sucursal puede ser 000, y es válida.
- El campo _Código Postal_ podría estar presente, opcional. Es útil cuando se quiere reportar, por ejemplo, las provincias más riesgosas en términos financieros. Un dato curioso basado en nuestra experiencia es que, en esta época, la provincias de Tucumán, Salta y alrededores tienen un porcentaje mucho más alto de rechazo que el resto. Al menos en nuestro rubro, esto es así, y saberlo nos permite organizar mejor nuestras finanzas.
- El campo _Monto_ debería estar ubicado posterior a las fechas de _Emisión_ y _Pago_, ya que ese es el orden visual que tiene un cheque, físicamente. Lo renombraría a _Importe_, por consistencia con el resto de los términos del sistema.
- Agregaría una regla de validación impidiendo la creación de cheques que compartan Banco, Sucursal y Número. Ya que casi seguramente se trata de un error de tipeo o de un intento de ingresar un cheque ya registrado.

De esa manera se puede ingresar un cheque navegando por los campos  con `TAB` y usando casi únicamente el teclado numérico. Se agiliza mucho el trabajo administrativo.
